const artists = [
  { name: "AA Murakami", url: "https://www.aamurakami.com/" },
  { name: "Aaron Penne", url: "https://www.aaronpenne.io/" },
  { name: "Alejandro Cartagena", url: "https://web.alejandrocartagena.com/" },
  { name: "Aleksandra Jovanic", url: "https://www.gorillasun.de/blog/in-conversation-with-aleksandra-jovanic/" },
  { name: "Alessandro Fiore", url: "https://www.gorillasun.de/blog/in-conversation-with-alessandro-fiore/" },
  { name: "Alex Supkay / Generative Artworks", url: "https://alexsupkay.com/" },
  { name: "Alexis Andre", url: "https://artynft.io/interviews/mactuitui-alexis-andre/" },
  { name: "Alida Sun", url: "https://www.rightclicksave.com/article/the-art-of-embodied-immersion-alida-sun-interview" },
  // { name: "Alkan Avcıoğlu", url: "https://alkanavcioglu.com/" },
  { name: "Amy Goodchild", url: "https://www.amygoodchild.com/" },
  { name: "Ana Carreras", url: "https://www.annacarreras.com/" },
  { name: "Ana Maria Caballero", url: "https://anamariacaballero.com/" },
  { name: "Andreas Gysin", url: "https://ertdfgcvb.xyz/" },
  { name: "Andreas Rau", url: "https://andreasrau.eu/index/" },
  { name: "Andrew Badr", url: "https://www.andrewbadr.com/" },
  // { name: "Andrew Mitchell", url: "https://andrewmitchell.xyz/?mode=1" },
  { name: "Anna Beller", url: "https://www.annabeller.de/" },
  { name: "Anna Lucia", url: "https://annalucia.io/" },
  { name: "Anna Ridler", url: "https://annaridler.com/" },
  { name: "Anna Ridler", url: "https://annaridler.com/" },
  { name: "Anne Spalter", url: "https://annespalter.com/" },
  { name: "Aranda/Lasch", url: "https://arandalasch.com/" },
  { name: "Aurece Vettier", url: "https://www.aurecevettier.com/" },
  { name: "Auriea Harvey", url: "https://auriea.art/" },
  { name: "Bart Simons", url: "https://www.bartsimons.com/" },
  { name: "beardcoded", url: "https://beardcoded.xyz/" },
  { name: "Ben Kovach", url: "https://bendotk.com/" },
  { name: "Ben Snell", url: "https://bensnell.io/" },
  { name: "Bjorn Staal", url: "https://void.as/" },
  { name: "Blair Simmons", url: "https://www.blairsimmons.com/about" },
  { name: "Boreta", url: "https://boreta.net/" },
  { name: "Botto", url: "https://botto.com/" },
  { name: "Brad Damico", url: "https://thehug.xyz/artists/artplusbrad/portfolio" },
  { name: "Bryan Brinkman", url: "https://www.bryanbrinkman.com/" },
  { name: "Camille Roux", url: "https://art.camilleroux.com/" },
  { name: "Casey Reas", url: "https://reas.com/" },
  { name: "Charlotte Dan", url: "https://charlottedann.com/" },
  { name: "Claudia Hart", url: "https://claudiahart.com/" },
  { name: "Clownvamp", url: "https://clownvamp.com/" },
  { name: "Connie Bakshi", url: "https://conniebakshi.com/" },
  { name: "Cory Arcangel", url: "https://coryarcangel.com/" },
  { name: "Cory Haber", url: "https://www.coryhaber.com/" },
  { name: "Dan Catt", url: "https://revdancatt.com/" },
  { name: "Deafbeef", url: "https://www.deafbeef.com/" },
  { name: "Dmitri Cherniak", url: "https://lightyears.fellowship.xyz/in-conversation/" },
  { name: "Eko33", url: "https://www.eko33.com/" },
  { name: "Emi Kusano", url: "https://www.emikusano.art/" },
  { name: "Emily Edelman", url: "https://www.emilyedelman.com/art" },
  { name: "Emily Weill", url: "https://www.studioemilyweil.com/" },
  { name: "Emily Xie", url: "https://emilyxie.art/" },
  { name: "encapsuled", url: "https://encapsuled.xyz/" },
  { name: "Entangled Others Studio", url: "https://entangledothers.studio/" },
  { name: "Eric Andwer", url: "https://www.andwer.xyz/" },
  { name: "Erick Calderon", url: "https://www.jeffgdavis.com/" },
  { name: "Erin Wajufros", url: "https://www.erinwajufos.digital/" },
  { name: "Fahad Karim", url: "https://www.fahadkarim.com/" },
  { name: "Feider Nake", url: "https://compart.uni-bremen.de/content/4-teaching/0-sommer-20/2-think-the-image-generative-art/3-material/paper-2010-nake_paragraphs.pdf" },
  { name: "Fingacode", url: "https://www.artpoint.fr/artists/fingacode" },
  { name: "Florian Zumbrunn", url: "https://www.florianzumbrunn.com/" },
  { name: "Ganbrood", url: "https://teia.art/Latent_Space" },
  { name: "Harm van den Dorpel", url: "https://harm.work/" },
  { name: "Harold Cohen", url: "https://www.aaronshome.com/aaron/index.html" },
  { name: "Harvey Rainer", url: "https://rayner.art/" },
  { name: "Heaven Computer", url: "https://heaven.computer/" },
  { name: "Holger Lippmann", url: "https://e-art.co/" },
  { name: "IANGAC", url: "https://iamnotgoodatcomputer.com/" },
  { name: "Iskra Velitchkova", url: "https://iskraovelitchkova.com/" },
  { name: "Ivona Tau", url: "https://ivonatau.com/welcome" },
  { name: "Jacek Markusiewicz", url: "https://www.rightclicksave.com/article/the-interview-jacek-markusiewicz-generative-art-architecture" },
  { name: "James Merrill", url: "https://www.lostpixels.io/" },
  { name: "Jan Robert Leetge", url: "https://www.leegte.org/work/jpeg/" },
  { name: "Jeff Davis", url: "https://www.jeffgdavis.com/" },
  { name: "Jen Lowe", url: "https://www.jenlowe.net/" },
  { name: "Jesse Draxler", url: "https://jessedraxler.com/" },
  { name: "Jimeno Buena Vida", url: "https://www.buenavidaart.com/" },
  { name: "Jiwa", url: "https://www.ntent.art/jiwa" },
  { name: "John Gerrard", url: "https://www.johngerrard.net/" },
  { name: "John Provencher", url: "https://johnprovencher.com/" },
  { name: "Jonathan Chomko", url: "https://jonathanchomko.com/" },
  { name: "Jorge Ledezma", url: "https://ledezma.art/en/" },
  { name: "Joshua Davis", url: "https://joshuadavis.com/" },
  { name: "Juan Pedro Vallejo", url: "https://medium.com/@juanpedro.vallejo/interferences-a92b0160f873" },
  { name: "Juan Rodriguez Garcia", url: "https://www.juanrg92.com/" },
  { name: "Julian Espagnon", url: "https://julienespagnon.fr/" },
  { name: "Julian Hesperheide", url: "https://www.julian-h.de/work/" },
  { name: "Kacey Weiniger", url: "https://kaceyweiniger.com/" },
  { name: "Kevin Abosch", url: "https://kevinabosch.com/" },
  // { name: "Kevin Esherick", url: "https://kevinesherick.substack.com/" },
  { name: "Kim Asendorf", url: "https://kimasendorf.com/" },
  { name: "Kjetil Golid", url: "https://generated.space/" },
  // { name: "Landlines Art", url: "https://tgam.xyz/artist/LandlinesArt" },
  { name: "Lars Wander", url: "https://www.larswander.com/" },
  { name: "Lars Wander", url: "https://www.larswander.com/" },
  { name: "Lauren Lee McCarthy", url: "https://lauren-mccarthy.com/" },
  { name: "Leander Herzog", url: "https://leanderherzog.ch/" },
  { name: "Leonardo Solaas", url: "https://solaas.com.ar/" },
  { name: "Lia", url: "https://www.liaworks.com/about/" },
  { name: "Licia He", url: "https://www.eyesofpanda.com/" },
  { name: "Linda Dounia", url: "https://lindarebeiz.com/" },
  { name: "Lovid", url: "https://www.lovid.org/" },
  { name: "Luke Shannon", url: "https://lukeshannon.xyz/" },
  // { name: "Manolo Gamboa Naon", url: "https://www.behance.net/manoloide?locale=en_US" },
  { name: "Marcel Schwittlick", url: "https://schwittlick.net/" },
  // { name: "Marcelo Soria Rodriguez", url: "https://marcelosoriarodriguez.org/" },
  { name: "Mario Carrillo", url: "https://marioecg.com/" },
  { name: "Mario Klingemann", url: "https://quasimondo.com/" },
  { name: "Mark Webster", url: "https://mwebster.online/" },
  { name: "Martijn Cohen", url: "https://www.martigeon.com/" },
  { name: "Martin Grasser", url: "https://martingrasser.com/" },
  { name: "Matt Deslaureiers", url: "https://www.mattdesl.com/" },
  { name: "Matt Jacobson", url: "https://iammattjacobson.com/information" },
  { name: "Matthieu Segret", url: "https://immutablecollective.art/matthieu-segret/" },
  { name: "matto matto", url: "https://material.work/" },
  { name: "Maya Man", url: "https://mayaontheinter.net/" },
  { name: "Melissa Wiederract", url: "https://www.melissawiederrecht.com/work" },
  { name: "Mia Forrest ", url: "https://www.mia-forrest.com/" },
  { name: "Michael Mandiberg", url: "https://www.mandiberg.com/" },
  { name: "Mieke Marple", url: "https://miekemarple.com/" },
  { name: "Minne Atairu", url: "https://minneatairu.com/" },
  { name: "Mitchell F Chan", url: "https://chan.gallery/" },
  { name: "MPKoz", url: "https://www.mpkoz.com/" },
  // { name: "Nat Sarkissian", url: "https://natsarkissian.com/" },
  // { name: "Nathaniel Stern", url: "https://nathanielstern.com/" },
  { name: "Ngozi", url: "https://www.ngozi-nao.com/" },
  { name: "Nicolas Daniel", url: "https://nicolasdaniel.com/" },
  { name: "Nicolas Sassoon", url: "https://nicolassassoon.com/" },
  { name: "Operator", url: "https://www.operator.la/" },
  { name: "Oxfff", url: "https://www.0xfff.love/" },
  { name: "OXHaiku", url: "https://haikugenius.ai/" },
  { name: "P1xelfool", url: "https://p1xelfool.com/" },
  { name: "Patricio Gonzales Vivo", url: "https://patriciogonzalezvivo.com/" },
  { name: "Piere Casadabaig", url: "https://art.casadebaig.net/" },
  { name: "Pindar van Arman", url: "https://www.vanarman.com/" },
  { name: "Piter Pasma", url: "https://piterpasma.nl/" },
  { name: "Pixel Symphony", url: "https://www.pixelsymphony.art/" },
  { name: "Qian Qian", url: "https://q2.work/" },
  { name: "Qubibi", url: "https://qubibi.org/" },
  { name: "Rafael Rozendaal", url: "https://www.newrafael.com/" },
  { name: "Rahul Iyer", url: "https://rahul.fun/" },
  { name: "RalenArc", url: "https://ralenarc.com/" },
  { name: "Refik Anadol", url: "https://www.newrafael.com/" },
  { name: "Robbie Barrat", url: "https://robbiebarrat.github.io/" },
  { name: "Roope Rainisto", url: "https://www.rooperainisto.com/" },
  { name: "Rosenlykke", url: "https://rosenlykke.com/" },
  { name: "Ross Goodwin", url: "https://rossgoodwin.com/" },
  { name: "Rudxane", url: "https://rudxane.shop/" },
  { name: "Sarah Friend", url: "https://isthisa.com/" },
  { name: "Sarah Meyohas", url: "https://sarahmeyohas.com/" },
  { name: "Sarah Ridgley", url: "https://sarahridgley.com/" },
  { name: "Sasha Stiles", url: "https://www.sashastiles.com/" },
  { name: "sgt-slaughtermelon", url: " https://sgtslaughtermelon.com/art/" },
  { name: "Simon Denny", url: "https://simondenny.net/" },
  { name: "Spalter Digital", url: "https://spalterdigital.com/" },
  // { name: "Spongenuity", url: "https://spongenuity.com/" },
  { name: "Stefano Contiero", url: "https://stefanocontiero.com/" },
  { name: "Sterling Crispin", url: "https://www.sterlingcrispin.com/" },
  { name: "Steve Pikelny", url: "https://steviep.xyz/" },
  { name: "Tabor Robak", url: "https://www.taborrobak.com/" },
  // { name: "Takawo Shunsuke", url: "https://openprocessing.org/user/6533/?view=sketches#sketches" },
  // { name: "Tamara Moura Costa", url: "https://sites.google.com/view/tamamoyre" },
  { name: "Thomas Lin Pederson", url: "https://thomaslinpedersen.art/" },
  { name: "Thomas Noya", url: "https://www.thomasnoya.com/" },
  { name: "Tyler Hobbs", url: "https://www.tylerxhobbs.com/" },
  { name: "Vera Molnar", url: "https://ropac.net/artists/231-vera-molnar/" },
  { name: "Victor Doval", url: "https://produccionesluminosas.blogspot.com/" },
  // { name: "White Koala", url: "https://whitekoala.art/" },
  { name: "William Mapan", url: "https://www.rightclicksave.com/article/an-interview-with-william-mapan" },
  { name: "William Watkins", url: "https://wwatkns.art/projects" },
  { name: "YKXOTKX", url: "https://ykxotkx.art/" },
  // { name: "Yung Wknd", url: "https://www.yungwknd.xyz/" },
  { name: "Zach Lieberman", url: "http://zach.li/" },
  { name: "Zancan ", url: "https://zancan.art/" },
  { name: "Ian Goodfellow", url: "https://www.iangoodfellow.com/" },
  { name: "Ruby Justice Thelot", url: "https://asterisques.com/" },
  { name: "Spencer Chang", url: "https://spencer.place/" },
  { name: "Shelby Wilson", url: "https://shelby.cool/" },
  { name: "Maxwell Neely-Cohen", url: "https://maxy.world/" },
  { name: "Petra Cortright", url: "https://www.petracortright.com/" },
  { name: "Molly Soda", url: "https://mollysoda.exposed/" },
  { name: "Monica Rizzoli", url: "https://monicarizzolli.io/" },
  { name: "Robert Alice", url: "https://www.robertalice.com/" },
  { name: "Hans Dehlinger", url: "https://generativeart.de/index.php/de/" },
  { name: "PAWEŁ DUDKO", url: "https://pdudko.com/" },
  { name: "Gine Choy", url: "https://www.ginachoy.com/" },
  { name: "Nicole Vella", url: "https://www.nicolevella.com/" },
  { name: "Clay Devlin", url: "https://www.coincidence.studio/" },
  // { name: "niceaunties", url: "https://www.niceaunties.com/" },
  { name: "Geoff Davis", url: "https://geoffdavis.org/" },
  { name: "heeey", url: "https://heeey.art/" },
  { name: "Margaret Murphy", url: "https://margaretmurphy.xyz/" },
  { name: "Holly&Mat", url: "https://herndondryhurst.studio/" },
  // { name: "Manuel Lorino", url: "https://mlarino.com/" },
  { name: "Nolen Royalty", url: "https://eieio.games/" },
  { name: "Carla Gannis", url: "https://carlagannis.com/" },
  { name: "Mika Ben Amar", url: "https://post.technology/" },
  { name: "Jennifer and Kevin McCoy", url: "https://www.mccoyspace.com/" },
  { name: "LaTurbo Avadon", url: "https://www.laturboavedon.com/" },
  { name: "Sara Ludy", url: "https://www.saraludy.com/" },
  { name: "Jonas Lund", url: "https://jonaslund.com/" },
  { name: "riiiis", url: "https://riiiis.xyz/" }
];

const sources = [
  { name: "Art Blocks", url: "https://www.artblocks.io/" },
  { name: "Bright Moments", url: "https://www.brightmoments.io/" },
  { name: "Book of Shaders", url: "https://thebookofshaders.com/" },
  { name: "Verse", url: "https://verse.works/" },
  { name: "Ensemble", url: "https://www.ensemble.art/" },
  { name: "Tender", url: "https://tender.art/artworks" },
  { name: "Expanded.Art", url: "https://www.expanded.art/" },
  { name: "Glitch Marfa", url: "https://www.glitchmarfa.com/" },
  { name: "Nguyen Wahed", url: "https://nguyenwahed.com/" },
  { name: "The Coding Train", url: "https://thecodingtrain.com/" },
  { name: "p5.js website", url: "https://p5js.org/" },
  { name: "Open Processing", url: "https://openprocessing.org/" },
  { name: "Trame", url: "https://trameparis.com/" },
  { name: "ArtxCode", url: "https://www.artxcode.io/" },
  // { name: "LeRandom", url: "https://www.lerandom.art/" },
  // { name: "Heft", url: "https://heftgallery.com/" },
  { name: "Kate Vass", url: "https://www.katevassgalerie.com/" },
  { name: "NFC Lisbon", url: "https://www.nonfungibleconference.com/" },
  { name: "Plottables", url: "https://plottables.io/" },
  { name: "Transfer", url: "https://transfer.art/" },
  { name: "Postmasters", url: "https://www.postmastersart.com/" },
  // { name: "Francesca Franco", url: "https://www.francescafranco.net/index.html" },
  { name: "Aleksandra Art", url: "https://www.aleksandra.art/amonovskaja" },
  { name: "bitforms", url: "https://www.bitforms.art/" }
];